# 스냅챌 MVP 퀘스트 데이터 (문서 기반 사전 생성)

QUEST_TEMPLATES = [
    # ============ 친구 모드 퀘스트 ============
    {
        "quest_id": "FQ-001",
        "mode": "friend",
        "title": "무지개 로그",
        "short_description": "시간마다 다른 색을 찾아요.",
        "full_description": "하루 동안 색깔을 하나씩 찾아가며 일상을 기록하는 로그입니다.",
        "tone": "가볍고 찾는 재미",
        "difficulty": "easy",
        "fallback": True,
        "tags": ["color", "daily", "find"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "빨강", "instruction": "빨간색 물건을 찾아라!!", "example": "소화전, 컵, 포스터"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "다홍", "instruction": "다홍빛을 찾아라!!", "example": "간판, 립밤, 스티커"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "주황", "instruction": "주황색 물건은 어디?", "example": "과자 봉지, 펜, 가방"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "살구", "instruction": "살구색을 찾아라!!", "example": "벽지, 파우치, 노트"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "노랑", "instruction": "노란색을 포착하라!!", "example": "조명, 표지판, 파일"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "연두", "instruction": "연두색을 찾아라!!", "example": "잎, 형광펜, 라벨"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "초록", "instruction": "초록색 물건은?", "example": "나무, 음료, 옷"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "민트", "instruction": "민트색을 찾아라!!", "example": "케이스, 컵, 간판"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "하늘", "instruction": "하늘색을 찾아라!!", "example": "하늘, 셔츠, 포스터"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "파랑", "instruction": "파란색을 포착하라!!", "example": "물병, 가방, 표지"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "남색", "instruction": "남색 물건은 어디?", "example": "옷, 책, 지갑"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "보라", "instruction": "보라색을 찾아라!!", "example": "조명, 스티커, 꽃"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "자주", "instruction": "자주색을 포착하라!!", "example": "파우치, 간판, 소품"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "분홍", "instruction": "분홍색 물건은?", "example": "케이스, 포장지, 컵"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "갈색", "instruction": "갈색을 찾아라!!", "example": "책상, 가방, 커피"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "베이지", "instruction": "베이지색은 어디?", "example": "벽, 옷, 종이"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "회색", "instruction": "회색 물건을 찾아라!!", "example": "노트북, 바닥, 의자"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "흑백", "instruction": "검정이나 흰색은?", "example": "키보드, 신발, 문"},
        ]
    },
    {
        "quest_id": "FQ-002",
        "mode": "friend",
        "title": "같은 포즈 챌린지",
        "short_description": "시간마다 정해진 포즈를 각자 해봐요.",
        "full_description": "시간마다 정해진 포즈를 각자 해보는 로그입니다.",
        "tone": "장난스럽고 따라 하기 쉬움",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["pose", "follow", "friend"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "볼하트", "instruction": "볼하트를 보여라!", "example": "볼하트"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "손가락 하트", "instruction": "손가락 하트 발사!", "example": "손가락 하트"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "브이", "instruction": "최고의 브이는?", "example": "브이 포즈"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "턱받침", "instruction": "턱 괴고 멈춰라!", "example": "턱받침"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "놀란 표정", "instruction": "놀란 얼굴 가자!", "example": "눈 크게 뜨기"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "윙크", "instruction": "윙크 한 번!", "example": "윙크"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "엄지척", "instruction": "엄지척을 날려라!", "example": "엄지척"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "손인사", "instruction": "손인사 보내라!", "example": "손 흔들기"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "입술 쭉", "instruction": "입술 쭉 내밀기!", "example": "장난 표정"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "눈 가리기", "instruction": "한쪽 눈을 가려라!", "example": "손으로 눈 가리기"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "머리 위 하트", "instruction": "머리 위 하트!", "example": "큰 하트"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "고개 갸웃", "instruction": "고개를 갸웃!", "example": "갸웃 포즈"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "팔짱", "instruction": "팔짱 끼고 등장!", "example": "팔짱"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "손바닥", "instruction": "손바닥을 보여라!", "example": "손바닥 클로즈업"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "쉿", "instruction": "조용히 쉿!", "example": "쉿 포즈"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "피곤 포즈", "instruction": "피곤함을 표현하라!", "example": "축 처진 표정"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "자신감 포즈", "instruction": "자신감 있게!", "example": "당당한 포즈"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "자유 포즈", "instruction": "마지막 포즈는 자유!", "example": "각자 포즈"},
        ]
    },
    {
        "quest_id": "FQ-003",
        "mode": "friend",
        "title": "내 주변 가장 웃긴 거",
        "short_description": "주변에서 제일 웃긴 순간을 찾아요.",
        "full_description": "지금 주변에서 가장 웃긴 장면을 찾는 로그입니다.",
        "tone": "웃김, 즉흥적",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["funny", "find", "daily"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "웃긴 물건", "instruction": "웃긴 물건을 찾아라!", "example": "스티커, 소품"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "이상한 조합", "instruction": "이상한 조합은?", "example": "책상 위 물건"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "웃긴 표정", "instruction": "웃긴 표정 가자!", "example": "표정 연기"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "삐뚤어진 것", "instruction": "삐뚤어진 걸 찾아라!", "example": "비뚤어진 포스터"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "웃긴 글자", "instruction": "웃긴 글자는 어디?", "example": "간판, 메모"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "애매한 물건", "instruction": "이게 왜 여기 있지?", "example": "뜬금없는 물건"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "웃긴 각도", "instruction": "이상한 각도로!", "example": "아래에서 보기"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "예상 밖 장면", "instruction": "예상 밖 순간은?", "example": "친구 행동, 상황"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "이상한 그림자", "instruction": "이상한 그림자 찾기!", "example": "벽, 바닥"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "오늘의 밈", "instruction": "밈 같은 장면은?", "example": "표정, 상황"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "웃긴 소품", "instruction": "웃긴 소품을 찾아라!", "example": "인형, 장식"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "난감한 순간", "instruction": "난감함을 보여라!", "example": "빈 컵, 엉킨 선"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "웃긴 손", "instruction": "손으로 웃겨라!", "example": "손 포즈"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "무해한 웃김", "instruction": "귀여운 웃김은?", "example": "작은 실수, 소품"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "이상한 자세", "instruction": "이상한 자세 가자!", "example": "구부정 자세"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "오늘의 허탈", "instruction": "허탈함을 표현하라!", "example": "빈 접시, 누운 자세"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "웃긴 클로즈업", "instruction": "가까이 보면 웃긴 것!", "example": "물건 확대"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘의 웃김", "instruction": "오늘의 웃김 결산!", "example": "자유"},
        ]
    },
    {
        "quest_id": "FQ-004",
        "mode": "friend",
        "title": "공통 주제 로그",
        "short_description": "같은 질문에 각자 다르게 답해요.",
        "full_description": "같은 질문에 각자 다른 장면으로 답하는 로그입니다.",
        "tone": "가볍고 대화 소재가 생김",
        "difficulty": "easy",
        "fallback": True,
        "tags": ["common", "preference", "daily"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "오늘의 시작", "instruction": "하루 시작은 무엇?", "example": "침대, 창문"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "오늘의 색", "instruction": "오늘의 색은?", "example": "옷, 하늘, 물건"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "오늘의 신발", "instruction": "오늘 신발 공개!", "example": "운동화, 슬리퍼"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "오늘의 책상", "instruction": "지금 책상 상태는?", "example": "책상, 노트"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "오늘의 음료", "instruction": "지금 마시는 것은?", "example": "물, 커피"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "오늘의 물건", "instruction": "손에 잡힌 물건은?", "example": "펜, 폰, 키"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "오늘의 점심", "instruction": "점심의 흔적은?", "example": "식판, 포장지"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "오늘의 하늘", "instruction": "지금 하늘은?", "example": "창밖, 구름"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "오늘의 집중", "instruction": "집중한 흔적은?", "example": "노트, 화면 밖 물건"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "오늘의 간식", "instruction": "간식 타임은?", "example": "과자, 젤리"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "오늘의 피곤", "instruction": "피곤함을 보여라!", "example": "커피, 자세"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "오늘의 이동", "instruction": "어디로 가는 중?", "example": "버스, 길, 신발"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "오늘의 저녁", "instruction": "저녁의 힌트는?", "example": "메뉴판, 접시"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "오늘의 기분", "instruction": "기분을 한손으로!", "example": "엄지, 하트"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "오늘의 자랑", "instruction": "작은 자랑은?", "example": "완료한 일"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "오늘의 소리", "instruction": "지금 들리는 것은?", "example": "이어폰, 창문"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "오늘의 공간", "instruction": "지금 있는 곳은?", "example": "방, 카페"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘의 마무리", "instruction": "하루 마무리는?", "example": "조명, 침대"},
        ]
    },
    {
        "quest_id": "FQ-005",
        "mode": "friend",
        "title": "우리는 하나 컨셉",
        "short_description": "각자 다른 조각으로 하나를 완성해요.",
        "full_description": "각자 다른 조각을 찍어 하나의 컨셉을 완성하는 로그입니다.",
        "tone": "협동, 엉뚱함",
        "difficulty": "normal",
        "fallback": False,
        "tags": ["coop", "piece", "friend"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "머리 위", "instruction": "머리 위만 보여라!", "example": "머리카락, 모자"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "이마", "instruction": "이마 구역 공개!", "example": "이마, 앞머리"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "눈", "instruction": "눈만 보여라!", "example": "눈, 안경"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "코", "instruction": "코 구역 담당!", "example": "코 클로즈업"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "입", "instruction": "입으로 표현하라!", "example": "웃는 입"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "턱", "instruction": "턱선을 맡아라!", "example": "턱, 목"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "손", "instruction": "손으로 말하라!", "example": "손 모양"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "발", "instruction": "발 위치 공개!", "example": "신발, 발끝"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "옷 소매", "instruction": "소매만 보여라!", "example": "셔츠, 후드"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "가방", "instruction": "가방 조각 담당!", "example": "가방, 파우치"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "책상 조각", "instruction": "책상 한 칸 공개!", "example": "책상 모서리"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "배경 조각", "instruction": "배경만 맡아라!", "example": "벽, 창문"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "그림자", "instruction": "그림자로 참여!", "example": "바닥 그림자"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "실루엣", "instruction": "실루엣만 보여라!", "example": "역광, 옆모습"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "색 조각", "instruction": "오늘 색 한 조각!", "example": "옷 색, 물건"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "표정 조각", "instruction": "표정 한 조각!", "example": "눈웃음, 입꼬리"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "손끝", "instruction": "손끝만 등장!", "example": "손가락, 반지"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "전체 마무리", "instruction": "마지막 조각 완성!", "example": "자유"},
        ]
    },
    {
        "quest_id": "FQ-006",
        "mode": "friend",
        "title": "금지 장면 게임",
        "short_description": "금지 장면을 피해서 찍는 게임이에요.",
        "full_description": "정해진 금지 장면을 피해서 찍는 게임형 로그입니다.",
        "tone": "게임, 눈치, 장난",
        "difficulty": "normal",
        "fallback": False,
        "tags": ["game", "forbidden", "friend"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "음식 금지", "instruction": "음식 없이 찍어라!", "example": "창밖, 손"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "얼굴 금지", "instruction": "얼굴 없이 보여라!", "example": "물건, 풍경"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "책상 금지", "instruction": "책상은 피하라!", "example": "벽, 바닥"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "음료 금지", "instruction": "음료는 금지!", "example": "가방, 길"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "화면 금지", "instruction": "화면 없이 찍어라!", "example": "주변 사물"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "손 금지", "instruction": "손을 숨겨라!", "example": "풍경, 물건"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "글자 금지", "instruction": "글자 없는 장면!", "example": "하늘, 바닥"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "신발 금지", "instruction": "신발은 빼라!", "example": "상체, 물건"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "가방 금지", "instruction": "가방 없이 보여라!", "example": "길, 책"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "하늘 금지", "instruction": "하늘은 피하라!", "example": "실내, 책상 밖"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "검정 금지", "instruction": "검정색 금지!", "example": "밝은 물건"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "셀카 금지", "instruction": "셀카는 금지!", "example": "시선 밖 장면"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "음식점 금지", "instruction": "음식점 느낌 금지!", "example": "길, 손잡이"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "침대 금지", "instruction": "침대는 피하라!", "example": "책, 창문"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "문 금지", "instruction": "문 없이 찍어라!", "example": "벽, 소품"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "의자 금지", "instruction": "의자는 금지!", "example": "바닥, 책상 밖"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "동그라미 금지", "instruction": "동그라미 피하기!", "example": "각진 물건"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘 금지 복습", "instruction": "제일 어려운 금지는?", "example": "자유"},
        ]
    },
    # ============ 커플 모드 퀘스트 ============
    {
        "quest_id": "CQ-001",
        "mode": "couple",
        "title": "같은 하루 다른 시선",
        "short_description": "같은 주제를 각자의 시선으로 기록해요.",
        "full_description": "같은 주제를 각자의 시선으로 기록하는 로그입니다.",
        "tone": "따뜻함, 비교하는 재미",
        "difficulty": "easy",
        "fallback": True,
        "tags": ["couple", "daily", "perspective"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "아침 시선", "instruction": "눈뜨자마자 보이는 건?", "example": "천장, 창문"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "오늘의 색", "instruction": "오늘의 색은?", "example": "옷, 하늘"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "출발 장면", "instruction": "출발의 순간은?", "example": "신발, 문"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "지금 내 앞", "instruction": "지금 내 앞은?", "example": "책상, 길"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "손에 든 것", "instruction": "손에 든 건?", "example": "컵, 폰"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "오늘의 빛", "instruction": "지금 빛은 어떤데?", "example": "햇빛, 조명"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "점심 힌트", "instruction": "점심 힌트는?", "example": "메뉴판, 접시"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "걷는 길", "instruction": "지금 길은?", "example": "보도블럭, 복도"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "집중 장면", "instruction": "집중의 흔적은?", "example": "노트, 펜"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "쉬는 순간", "instruction": "쉬는 순간 공개!", "example": "음료, 의자"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "시선 끝", "instruction": "눈길 끝에는?", "example": "창밖, 소품"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "퇴근/하교 느낌", "instruction": "끝나가는 느낌은?", "example": "가방, 신발"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "저녁 색", "instruction": "저녁의 색은?", "example": "노을, 조명"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "보여주고 싶은 것", "instruction": "이건 보여주고 싶다!", "example": "음식, 풍경"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "지금 공간", "instruction": "지금 공간은?", "example": "방, 카페"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "오늘의 온도", "instruction": "오늘 온도는?", "example": "담요, 음료"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "밤의 시선", "instruction": "밤에 보이는 건?", "example": "조명, 창문"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "하루 끝", "instruction": "하루 끝 장면은?", "example": "침대, 불빛"},
        ]
    },
    {
        "quest_id": "CQ-002",
        "mode": "couple",
        "title": "서로에게 보내는 순간",
        "short_description": "말 대신 짧은 장면으로 마음을 보내요.",
        "full_description": "말 대신 짧은 장면으로 마음을 보내는 로그입니다.",
        "tone": "다정함, 부담 없는 표현",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["couple", "heart", "message"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "아침 인사", "instruction": "아침 인사를 보내라!", "example": "손인사, 창문"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "오늘 출발", "instruction": "출발 인증!", "example": "신발, 가방"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "나 지금 여기", "instruction": "지금 있는 곳은?", "example": "학교, 회사"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "응원", "instruction": "응원을 보내라!", "example": "엄지척, 하트"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "생각났어", "instruction": "생각난 순간은?", "example": "좋아하는 물건"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "작은 안부", "instruction": "지금 괜찮아?", "example": "표정, 손"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "밥 먹었어?", "instruction": "밥의 흔적은?", "example": "식판, 컵"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "쉬어가기", "instruction": "쉬는 장면 보내기!", "example": "의자, 음료"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "보고 싶은 것", "instruction": "보여주고 싶은 것!", "example": "하늘, 소품"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "당 충전", "instruction": "당 충전 했어?", "example": "간식, 음료"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "오늘의 손", "instruction": "손으로 말해라!", "example": "하트, 브이"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "수고했어", "instruction": "수고한 흔적은?", "example": "가방, 책"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "저녁 인사", "instruction": "저녁 인사 보내라!", "example": "길, 조명"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "오늘의 웃음", "instruction": "웃음 한 조각!", "example": "표정, 상황"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "지금의 마음", "instruction": "마음을 한손으로!", "example": "손하트, 엄지"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "오늘의 위로", "instruction": "위로를 보내라!", "example": "담요, 조명"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "자기 전 힌트", "instruction": "잘 준비 됐어?", "example": "이불, 조명"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "잘 자 인사", "instruction": "잘 자 인사 보내라!", "example": "손인사, 불 끄기"},
        ]
    },
    {
        "quest_id": "CQ-003",
        "mode": "couple",
        "title": "취향 교환 로그",
        "short_description": "각자의 취향을 장면으로 공유해요.",
        "full_description": "각자의 취향을 장면으로 공유하는 로그입니다.",
        "tone": "귀엽고 가벼움",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["couple", "preference", "share"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "아침 취향", "instruction": "아침에 고른 것은?", "example": "음료, 옷"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "오늘의 향", "instruction": "오늘의 향 느낌은?", "example": "향수, 비누"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "오늘의 옷", "instruction": "오늘 옷 한 조각!", "example": "소매, 신발"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "오늘의 가방", "instruction": "가방 속 힌트는?", "example": "파우치, 책"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "오늘의 음료", "instruction": "오늘 음료는?", "example": "커피, 물"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "오늘의 색감", "instruction": "마음에 든 색감은?", "example": "하늘, 물건"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "오늘의 메뉴", "instruction": "오늘 메뉴 공개!", "example": "접시, 메뉴판"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "오늘의 음악", "instruction": "음악 느낌을 보여라!", "example": "이어폰, 창밖"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "좋아하는 질감", "instruction": "만지고 싶은 질감은?", "example": "천, 종이"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "간식 취향", "instruction": "간식 취향 공개!", "example": "과자, 빵"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "오늘의 소품", "instruction": "오늘 소품은?", "example": "키링, 펜"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "자주 보는 것", "instruction": "자주 보는 건?", "example": "화면 밖 사물"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "저녁 취향", "instruction": "저녁 취향은?", "example": "음식, 조명"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "좋아하는 공간", "instruction": "좋아하는 공간은?", "example": "방, 카페"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "오늘의 물건", "instruction": "오늘의 물건 하나!", "example": "컵, 책"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "편한 순간", "instruction": "편한 느낌은?", "example": "담요, 의자"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "밤 취향", "instruction": "밤에 어울리는 건?", "example": "조명, 음악"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘의 픽", "instruction": "오늘의 원픽은?", "example": "자유"},
        ]
    },
    {
        "quest_id": "CQ-004",
        "mode": "couple",
        "title": "만나는 날 로그",
        "short_description": "만나는 날을 각자 다른 시야로 기록해요.",
        "full_description": "만나는 날의 과정을 각자 다른 시야로 기록하는 로그입니다.",
        "tone": "기록, 설렘",
        "difficulty": "normal",
        "fallback": False,
        "tags": ["couple", "date", "meet"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "만남 예고", "instruction": "오늘 만날 준비?", "example": "알람, 옷"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "준비 시작", "instruction": "준비의 첫 장면!", "example": "거울, 가방"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "오늘의 착장", "instruction": "오늘 착장 힌트!", "example": "소매, 신발"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "챙긴 것", "instruction": "챙긴 물건은?", "example": "지갑, 선물"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "이동 시작", "instruction": "출발했다!", "example": "문, 신발"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "가는 길", "instruction": "가는 길 공개!", "example": "지하철, 길"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "기다리는 순간", "instruction": "기다리는 중?", "example": "시계, 장소"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "첫 장소", "instruction": "첫 장소는 어디?", "example": "카페, 거리"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "같은 공간", "instruction": "같은 공간 다른 시선!", "example": "테이블, 창"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "같이 본 것", "instruction": "같이 본 건?", "example": "영화표, 풍경"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "산책 장면", "instruction": "걷는 길은?", "example": "발, 길"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "오늘의 손", "instruction": "손의 순간은?", "example": "손, 물건"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "저녁 장면", "instruction": "저녁의 힌트!", "example": "메뉴, 조명"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "하이라이트", "instruction": "오늘 하이라이트!", "example": "음식, 웃음"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "아쉬운 순간", "instruction": "아쉬움은 어디?", "example": "역, 길"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "돌아가는 길", "instruction": "돌아가는 길은?", "example": "버스, 밤길"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "남은 흔적", "instruction": "오늘 남은 흔적!", "example": "영수증, 사진"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "만남 마무리", "instruction": "오늘 마무리!", "example": "조명, 방"},
        ]
    },
    {
        "quest_id": "CQ-005",
        "mode": "couple",
        "title": "서로 따라하기",
        "short_description": "상대가 할 법한 포즈나 장면을 따라해요.",
        "full_description": "상대가 할 법한 포즈나 장면을 따라 해보는 로그입니다.",
        "tone": "장난, 친밀함",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["couple", "follow", "pose"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "상대 아침", "instruction": "상대의 아침 표정!", "example": "졸린 표정"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "상대 포즈", "instruction": "상대 포즈 따라하기!", "example": "브이, 턱받침"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "상대 말투", "instruction": "상대 말투를 장면으로!", "example": "손짓, 표정"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "상대 취향", "instruction": "상대가 고를 물건은?", "example": "음식, 색"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "상대 습관", "instruction": "상대 습관 따라하기!", "example": "손동작"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "상대 시선", "instruction": "상대라면 볼 장면!", "example": "풍경, 소품"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "상대 메뉴", "instruction": "상대가 고를 메뉴는?", "example": "음식, 메뉴판"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "상대 웃음", "instruction": "상대 웃음 따라하기!", "example": "웃는 표정"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "상대 집중", "instruction": "상대 집중 모드!", "example": "책, 노트"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "상대 간식", "instruction": "상대 간식 픽은?", "example": "과자, 빵"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "상대 손짓", "instruction": "상대 손짓 따라하기!", "example": "손인사, 하트"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "상대 걷기", "instruction": "상대 걷는 느낌!", "example": "발, 길"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "상대 색", "instruction": "상대의 색은?", "example": "옷, 소품"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "상대 리액션", "instruction": "상대 리액션 따라하기!", "example": "놀람, 웃음"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "상대 휴식", "instruction": "상대 쉬는 방식은?", "example": "의자, 담요"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "상대 표정", "instruction": "그 표정 따라하기!", "example": "무표정, 미소"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "둘만 아는 것", "instruction": "둘만 아는 힌트!", "example": "장소, 물건"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘의 따라쟁이", "instruction": "오늘 최고 따라쟁이!", "example": "자유"},
        ]
    },
    {
        "quest_id": "CQ-006",
        "mode": "couple",
        "title": "오늘의 마음 날씨",
        "short_description": "오늘 감정 상태를 날씨처럼 표현해요.",
        "full_description": "오늘의 감정 상태를 날씨처럼 표현하는 로그입니다.",
        "tone": "다정하지만 과하지 않음",
        "difficulty": "easy",
        "fallback": False,
        "tags": ["couple", "emotion", "daily"],
        "missions": [
            {"order": 1, "hour_slot": "06:00", "mission_title": "아침 하늘", "instruction": "아침 마음 날씨는?", "example": "창밖, 표정"},
            {"order": 2, "hour_slot": "07:00", "mission_title": "맑음", "instruction": "맑았던 순간은?", "example": "햇빛, 웃음"},
            {"order": 3, "hour_slot": "08:00", "mission_title": "구름", "instruction": "살짝 흐린 건?", "example": "책상, 창문"},
            {"order": 4, "hour_slot": "09:00", "mission_title": "바람", "instruction": "정신없는 순간은?", "example": "이동, 사람들"},
            {"order": 5, "hour_slot": "10:00", "mission_title": "햇살", "instruction": "기분 좋아진 건?", "example": "커피, 빛"},
            {"order": 6, "hour_slot": "11:00", "mission_title": "안개", "instruction": "애매한 기분은?", "example": "흐린 창, 책상"},
            {"order": 7, "hour_slot": "12:00", "mission_title": "소나기", "instruction": "갑자기 지친 순간!", "example": "의자, 가방"},
            {"order": 8, "hour_slot": "13:00", "mission_title": "무지개", "instruction": "그래도 좋았던 건?", "example": "간식, 메시지"},
            {"order": 9, "hour_slot": "14:00", "mission_title": "더움", "instruction": "뜨거운 순간은?", "example": "햇빛, 음료"},
            {"order": 10, "hour_slot": "15:00", "mission_title": "선선함", "instruction": "편해진 순간은?", "example": "바람, 의자"},
            {"order": 11, "hour_slot": "16:00", "mission_title": "천둥", "instruction": "깜짝 놀란 건?", "example": "표정, 상황"},
            {"order": 12, "hour_slot": "17:00", "mission_title": "노을", "instruction": "노을 같은 순간은?", "example": "하늘, 조명"},
            {"order": 13, "hour_slot": "18:00", "mission_title": "비", "instruction": "축 처진 기분은?", "example": "커피, 책상"},
            {"order": 14, "hour_slot": "19:00", "mission_title": "별", "instruction": "반짝인 순간은?", "example": "조명, 소품"},
            {"order": 15, "hour_slot": "20:00", "mission_title": "달", "instruction": "조용한 마음은?", "example": "창문, 방"},
            {"order": 16, "hour_slot": "21:00", "mission_title": "포근함", "instruction": "포근한 건 뭐야?", "example": "담요, 침대"},
            {"order": 17, "hour_slot": "22:00", "mission_title": "밤공기", "instruction": "밤공기 느낌은?", "example": "창밖, 길"},
            {"order": 18, "hour_slot": "23:00", "mission_title": "오늘의 날씨", "instruction": "오늘 마음 총평!", "example": "자유"},
        ]
    },
]
